import type { Metadata } from "next";
import { Inter, Outfit  } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import FooterSection from "./components/footer/FooterSection";
import ApolloWrapper from "@/lib/ApolloClient/ApolloWrapper";
import Link from "next/link";

// Load the Inter font with proper variable handling
const inter = Inter({
  variable: "--font-inter", // This variable can be used in your CSS
  subsets: ["latin"],
});
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Link to Google Fonts for the Inter font */}
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&family=Outfit:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${inter.variable} antialiased`}>
        <ApolloWrapper>
          <Navbar />
          {children}
          <FooterSection />
        </ApolloWrapper>
      </body>
    </html>
  );
}
